-- ======================================================================
-- PRIMUS CAPITAL POC — Módulo 0: Setup
-- Crea la infraestructura base: database, schemas, warehouses, roles.
-- Ejecutar con SYSADMIN / ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

-- ======================================================================
-- DATABASE & SCHEMAS

CREATE DATABASE IF NOT EXISTS PRIMUS_POC;

CREATE SCHEMA IF NOT EXISTS PRIMUS_POC.RAW;
CREATE SCHEMA IF NOT EXISTS PRIMUS_POC.DWH;
CREATE SCHEMA IF NOT EXISTS PRIMUS_POC.COMPLIANCE;
CREATE SCHEMA IF NOT EXISTS PRIMUS_POC.SANDBOX;

-- ======================================================================
-- ## WAREHOUSES

CREATE WAREHOUSE IF NOT EXISTS PRIMUS_ETL_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'ETL y transformaciones — Medium para paralelización';

CREATE WAREHOUSE IF NOT EXISTS PRIMUS_ANALYTICS_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Queries BI — Small para 100 viewers Power BI + Qlik';

-- ======================================================================
-- ## ROLES

CREATE ROLE IF NOT EXISTS PRIMUS_ETL_ROLE
    COMMENT = 'Carga y transformación de datos';
CREATE ROLE IF NOT EXISTS PRIMUS_ANALYST_ROLE
    COMMENT = 'Consultas BI — PII enmascarada';
CREATE ROLE IF NOT EXISTS PRIMUS_COMPLIANCE_ROLE
    COMMENT = 'Compliance — acceso total a PII, puede pseudonimizar';

-- Jerarquía: SYSADMIN hereda todos los roles de la POC
GRANT ROLE PRIMUS_ETL_ROLE TO ROLE SYSADMIN;
GRANT ROLE PRIMUS_ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE PRIMUS_COMPLIANCE_ROLE TO ROLE SYSADMIN;

-- Grants sobre database
GRANT USAGE ON DATABASE PRIMUS_POC TO ROLE PRIMUS_ETL_ROLE;
GRANT USAGE ON DATABASE PRIMUS_POC TO ROLE PRIMUS_ANALYST_ROLE;
GRANT USAGE ON DATABASE PRIMUS_POC TO ROLE PRIMUS_COMPLIANCE_ROLE;

-- Grants sobre schemas
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TASK, CREATE STREAM, CREATE DYNAMIC TABLE
    ON SCHEMA PRIMUS_POC.RAW TO ROLE PRIMUS_ETL_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TASK, CREATE DYNAMIC TABLE
    ON SCHEMA PRIMUS_POC.DWH TO ROLE PRIMUS_ETL_ROLE;
GRANT USAGE ON SCHEMA PRIMUS_POC.DWH TO ROLE PRIMUS_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PRIMUS_POC TO ROLE PRIMUS_COMPLIANCE_ROLE;

-- Grants sobre warehouses
GRANT USAGE ON WAREHOUSE PRIMUS_ETL_WH TO ROLE PRIMUS_ETL_ROLE;
GRANT USAGE ON WAREHOUSE PRIMUS_ANALYTICS_WH TO ROLE PRIMUS_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE PRIMUS_ANALYTICS_WH TO ROLE PRIMUS_COMPLIANCE_ROLE;
GRANT USAGE ON WAREHOUSE PRIMUS_ETL_WH TO ROLE PRIMUS_COMPLIANCE_ROLE;

-- Para la POC, permitir al usuario actual usar todo
GRANT ROLE PRIMUS_ETL_ROLE TO USER JOCASTILLO;
GRANT ROLE PRIMUS_ANALYST_ROLE TO USER JOCASTILLO;
GRANT ROLE PRIMUS_COMPLIANCE_ROLE TO USER JOCASTILLO;

SELECT 'Setup completo: PRIMUS_POC database, 4 schemas, 2 warehouses, 3 roles' AS status;
